export const container: string;
export const headers: string;
export const count: string;
export const title: string;
export const textRow: string;
export const wrapperRow: string;
export const wrapperColumn: string;
export const textColor: string;
export const dot: string;
